In [1]:
# загрузка библиотеки pandas

import pandas as pd

In [2]:
# считать данные из таблицы weather.csv
# проверить первые 10 записей

frame = pd.read_csv('weather.csv')

In [4]:
# сколько строк в данных?
frame.shape

(96453, 12)

In [5]:
# первые 5 строк
frame.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [6]:
# первые 10 строк
frame.head(10)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
7,2006-04-01 07:00:00.000 +0200,Partly Cloudy,rain,8.772222,6.527778,0.89,14.1519,260.0,9.9820,0.0,1016.84,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.
9,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,13.772222,0.72,12.5258,279.0,9.9820,0.0,1017.22,Partly cloudy throughout the day.

In [7]:
# последние 5 строк
frame.tail()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [8]:
# последние 10 строк
frame.tail(10)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
96443,2016-09-09 14:00:00.000 +0200,Partly Cloudy,rain,30.894444,29.450000,0.28,14.7798,43.0,15.5526,0.0,1014.66,Partly cloudy starting in the morning.
96444,2016-09-09 15:00:00.000 +0200,Partly Cloudy,rain,31.083333,29.616667,0.28,15.5043,40.0,16.1000,0.0,1014.17,Partly cloudy starting in the morning.
96445,2016-09-09 16:00:00.000 +0200,Partly Cloudy,rain,31.083333,29.611111,0.28,13.8943,40.0,16.1000,0.0,1013.97,Partly cloudy starting in the morning.
96446,2016-09-09 17:00:00.000 +0200,Partly Cloudy,rain,30.766667,29.311111,0.28,14.2163,24.0,15.5526,0.0,1013.83,Partly cloudy starting in the morning.
96447,2016-09-09 18:00:00.000 +0200,Partly Cloudy,rain,28.838889,27.850000,0.32,12.2038,21.0,16.1000,0.0,1014.07,Partly cloudy starting in the morning.
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [10]:
# с 20 по 30 строки (включая 30 строку )
frame[20:31]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
20,2006-04-01 20:00:00.000 +0200,Mostly Cloudy,rain,11.550000,11.550000,0.77,7.3899,147.0,11.0285,0.0,1015.85,Partly cloudy throughout the day.
21,2006-04-01 21:00:00.000 +0200,Mostly Cloudy,rain,11.183333,11.183333,0.76,4.9266,160.0,9.9820,0.0,1015.77,Partly cloudy throughout the day.
22,2006-04-01 22:00:00.000 +0200,Partly Cloudy,rain,10.116667,10.116667,0.79,6.6493,163.0,15.8263,0.0,1015.40,Partly cloudy throughout the day.
23,2006-04-01 23:00:00.000 +0200,Mostly Cloudy,rain,10.200000,10.200000,0.77,3.9284,152.0,14.9569,0.0,1015.51,Partly cloudy throughout the day.
24,2006-04-10 00:00:00.000 +0200,Partly Cloudy,rain,10.422222,10.422222,0.62,16.9855,150.0,15.8263,0.0,1014.40,Mostly cloudy throughout the day.
25,2006-04-10 01:00:00.000 +0200,Partly Cloudy,rain,9.911111,7.566667,0.66,17.2109,149.0,15.8263,0.0,1014.20,Mostly cloudy throughout the day.
26,2006-04-10 02:00:00.000 +0200,Mostly Cloudy,rain,11.183333,11.183333,0.80,10.8192,163.0,14.9569,0.0,1008.71,Mostly cloudy throughout the day.
27,2006-04-10 03:00:00.000 +0200,Partly Cloudy,rain,7.155556,5.044444,0.79,11.0768,180.0,15.8263,0.0,1014.47,Mostly cloudy throughout the day.
28,2006-04-10 04:00:00.000 +0200,Partly Cloudy,rain,6.111111,4.816667,0.82,6.6493,161.0,15.8263,0.0,1014.45,Mostly cloudy throughout the day.
29,2006-04-10 05:00:00.000 +0200,Partly Cloudy,rain,6.788889,4.272222,0.83,13.0088,135.0,14.9569,0.0,1014.49,Mostly cloudy throughout the day.
30,2006-04-10 06:00:00.000 +0200,Mostly Cloudy,rain,7.261111,5.155556,0.85,11.1734,141.0,6.1985,0.0,1014.52,Mostly cloudy throughout the day.

In [23]:
# первые 10 строк поля Humidity
frame.loc[range(10),["Humidity"]]

   Humidity
0      0.89
1      0.86
2      0.89
3      0.83
4      0.83
5      0.85
6      0.95
7      0.89
8      0.82
9      0.72

In [25]:
# минимальное значение поля Humidity
frame['Humidity']. min()

0.0

In [26]:
# максимальное значение поля Humidity
frame['Humidity']. max()

1.0

In [28]:
# среднее значение поля Humidity
frame['Humidity']. mean()

0.7348989663358906

In [36]:
# температура, когда влажность минимальна
# d['Temperature (C)'][d['Humidity']==d['Humidity'].min()]
frame['Temperature (C)'][frame['Humidity']==frame['Humidity'].min()]

19958    -1.111111
28101   -15.000000
28103   -15.555556
28110   -13.888889
29627     1.111111
54840   -15.555556
54858   -15.000000
54870   -16.111111
54872   -15.000000
54873   -13.888889
55086   -12.777778
55088   -12.777778
55349   -12.222222
55350   -12.222222
55352   -12.222222
55412   -17.777778
55469   -17.777778
55472   -17.777778
55473   -16.111111
55481   -12.777778
55508   -16.111111
55511   -17.777778
Name: Temperature (C), dtype: float64

In [37]:
# температура, когда влажность максимальна
frame['Temperature (C)'][frame['Humidity']==frame['Humidity'].max()]

319      11.972222
342       7.155556
390       7.688889
535       5.933333
536      10.405556
           ...
95907    14.905556
96123     7.594444
96148     8.838889
96363    12.338889
96364    12.872222
Name: Temperature (C), Length: 2890, dtype: float64

In [40]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
Formatted Date              96453 non-null object
Summary                     96453 non-null object
Precip Type                 96453 non-null object
Temperature (C)             96453 non-null float64
Apparent Temperature (C)    96453 non-null float64
Humidity                    96453 non-null float64
Wind Speed (km/h)           96453 non-null float64
Wind Bearing (degrees)      96453 non-null float64
Visibility (km)             96453 non-null float64
Loud Cover                  96453 non-null float64
Pressure (millibars)        96453 non-null float64
Daily Summary               96453 non-null object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [38]:
# заполните все нулевые значения на 0
frame.fillna('0', inplace = True)

In [39]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
Formatted Date              96453 non-null object
Summary                     96453 non-null object
Precip Type                 96453 non-null object
Temperature (C)             96453 non-null float64
Apparent Temperature (C)    96453 non-null float64
Humidity                    96453 non-null float64
Wind Speed (km/h)           96453 non-null float64
Wind Bearing (degrees)      96453 non-null float64
Visibility (km)             96453 non-null float64
Loud Cover                  96453 non-null float64
Pressure (millibars)        96453 non-null float64
Daily Summary               96453 non-null object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB